server:
  port: 8060
  tomcat:
    max-swallow-size: -1
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 50MB
      enabled: true
      max-request-size: 50MB
      resolve-lazily: true