server:
  port: 8075
  servlet:
    context-path: '/leo-pay'
  tomcat:
    max-http-form-post-size: -1
spring:
  profiles:
    active: dev
  application:
    name: leo-pay
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  thymeleaf:
#    enabled: true
#    encoding: UTF-8
#    prefix: classpath:/templates/
#    suffix: .html
  servlet:
    multipart:
      max-file-size: 50MB
      enabled: true
      max-request-size: 50MB
      resolve-lazily: true
leo:
  debug:
    interface-call-statistics: false
    print-request-param: true
    print-to-result: false
    token-verify: false
    ignore-uri-list:
      - ${server.servlet.context-path}/doc.html
      - ${server.servlet.context-path}/swagger-resources
      - ${server.servlet.context-path}/webjars/**
  api:
    enable: true
    title: Leo pay 接口文档
    description: \# 接口调试页面。✍
    termsOfServiceUrl: http://www.acyou.cn/
    version: 1.0
    basePackage: cn.acyou.leo.pay.controller
    contact: youfang
# knife4j增强模式
knife4j:
  enable: true
  documents:
    - locations: classpath:knife4j_doc/*
      group: 1.0
      name: 文档手册
