ijpay:
  paypal:
    clientId: AbUnJc4ToUN7Z6lbnKB97rew653xvscUZks0FEU5Rw9Oqqd3PwNHokgrp47rkbNGjcQywhPKyYVT808o
    secret: EAFHSIydO8GJDvLah7Pb62NAFwit5fSHtmQHW6OanN4nccHnXte9gMmA662SvjCCJ__yfMQ89OFqUgl4
    sandBox: true
    domain: http://localhost:8075