spring:
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/scorpio?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: root123
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/scorpio2?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: root123
    sharding:
      default-data-source-name: ds0
      default-database-strategy:
        standard:
          shardingColumn: user_id
          preciseAlgorithmClassName: cn.acyou.leo.tool.sharding.algorithm.PreciseModuloShardingDatabaseAlgorithm
          rangeAlgorithmClassName: cn.acyou.leo.tool.sharding.algorithm.RangeModuloShardingDatabaseAlgorithm
        #inline: #不支持范围查询
        #  sharding-column: user_id
        #  algorithm-expression: ds$->{user_id % 2}
      binding-tables: t_order # 绑定表 • 绑定表适用于具有相同结构和访问模式的表
      broadcast-tables: t_param_config # 广播表 • 在分库分表以后，比如数据库1有配置表，数据库2有个配置表，数据库3也有个配置表，需要我们把配置同时写入三个数据库的配置表中， 在这样的情况下这里的配置表就是一种广播表，要求就是数据同步和一致。
      tables:
        t_order:
          actual-data-nodes: ds$->{0..1}.t_order_$->{0..1} # 分表： t_order_0 跟 t_order_1
          table-strategy:
            standard:
              shardingColumn: order_id
              preciseAlgorithmClassName: cn.acyou.leo.tool.sharding.algorithm.PreciseModuloShardingTableAlgorithm
              rangeAlgorithmClassName: cn.acyou.leo.tool.sharding.algorithm.RangeModuloShardingTableAlgorithm
            #inline:
            #  sharding-column: order_id # 按照order_id%2分别入t_order_0/t_order_1表
            #  algorithm-expression: t_order_$->{order_id % 2}
          # 主键生成策略（如果是自动生成的，在插入数据的sql中就不要传id，null也不行，直接插入字段中就不要有主键的字段）
          key-generator:
            column: order_id # order_id自动生成
            type: SNOWFLAKE
            props:
              worker:
                id: 1
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0