server:
  port: 8076
  servlet:
    context-path: '/leo-tool'
  tomcat:
    max-http-form-post-size: -1 #Tomcat不限制文件大小
  compression:
    # 开启 Controller 使用GZIP数据压缩
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    # 开启了 gzip 压缩，但是需要注意并不是说所有的接口都会使用 gzip 压缩，默认情况下，仅会压缩 `1024` 字节以上的内容
    min-response-size: 1024
spring:
  profiles:
    active: dev
    # active: sharding-databases-tables
  application:
    name: leo-tool
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    #default-property-inclusion: non_null
    #property-naming-strategy: SNAKE_CASE #对于fastjson缺省使用SnakeCase策略(统一对象参数下划线形式)
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML #LEGACYHTML5
  servlet:
    multipart:
      max-file-size: 50MB #由Servlet限制文件大小
      enabled: true
      max-request-size: 50MB #由Servlet限制文件大小
      resolve-lazily: true
  #mvc:
  #  async:
  #    request-timeout: 20000 # 设置请求超时时间为20000ms即20s
  mail:
    # host如果是qq就写qq，163就写163
    host: smtp.126.com
    port: 25
    username: iblog_admin@126.com
    # 这个密码就是smtp授权码
    password: WSZYRBCHSILMSVUW
    # 开启加密验证（这个只有qq有）
    properties:
      mail:
        smtp:
          auth: true
  flyway:
    # 开启Flyway
    enabled: true
    # 自动生成的flyway_schema_history表
    baseline-on-migrate: true
    # 检查迁移脚本位置是否存在。
    check-location: false
    # 是否允许无序迁移[开发true 生产false]（执行了新版本SQL再提交旧版本SQL会启动失败）
    out-of-order: true
  main:
    lazy-initialization: false # 延迟初始化（Bean懒加载）
leo:
  xxl-job:
    enable: false
  debug:
    interface-call-statistics: false
    print-performance-sql: true
    print-to-result: true
    print-request-info: true
    token-verify: false
    ignore-uri-list:
      - ${server.servlet.context-path}/doc.html
      - ${server.servlet.context-path}/swagger-resources
      - ${server.servlet.context-path}/v2/api-docs
      - ${server.servlet.context-path}/webjars/**
  api:
    enable: true
    title: Leo tool 接口文档
    description: \# 接口调试页面。✍
    termsOfServiceUrl: http://www.acyou.cn/
    version: 1.0
    basePackage: cn.acyou.leo.tool.controller
    contact: youfang
  xss:
    enabled: true
    excludes: /wx/verifyServer
  tool:
    tencent-map-key:
      key: VGKBZ-XXXXX-XXXXX-XXXXX-XXXXX-XXXXX
    email:
      username: iblog_admin@126.com
      password: WSZYRBCHSILMSVUW
      smtp-auth: true
      smtp-host: smtp.126.com
      smtp-port: 25
  extend-properties-paths: 'D:\workspace\work\private_account.properties'
  #extend-properties-paths: 'http://qiniu.acyou.cn/***/private_account1.properties'
  auto-create-db: true
# knife4j增强模式
knife4j:
  enable: true
  documents:
    - locations: classpath:knife4j_doc/*
      group: 1.0
      name: 文档手册
mybatis-plus:
  mapper-locations: classpath*:/mappers/**/*.xml
  type-aliases-package: cn.acyou.leo.tool.entity
  global-config:
    banner: false
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    # 结果集设置为HashMap，返回的字段值为null时，不会显示key，因为callSettersOnNulls默认为false
    call-setters-on-nulls: true
#分页pageHelper
pagehelper:
  helperDialect: mysql
  reasonable: false
  support-methods-arguments: false
  page-size-zero: false
retrofit:
  log:
    enable: true
    logging-interceptor: cn.acyou.leo.framework.retrofit.RetrofitClientRecords
    global-log-strategy: none
    global-log-level: info
  retry:
    # 不启用全局重试
    enable-global-retry: false
  global-read-timeout-ms: 60000
  global-call-timeout-ms: 0
  global-connect-timeout-ms: 60000
  global-write-timeout-ms: 60000

captcha:
  expire:
    default: 10000
    # 文字点选验证码 过期时间设置大一点
    WORD_IMAGE_CLICK: 60000
  cache:
    enabled: true
    cache-size: 20
  secondary:
    enabled: false
  # 不初始化默认的资源文件
  init-default-resource: false