spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scorpio?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 60000
      pool-name: springHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      data-source-properties:
        dataSource:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
      connection-init-sql: set names utf8mb4
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
mybatis-plus:
  mapper-locations: classpath*:/mappers/**/*.xml
  type-aliases-package: cn.acyou.leo.tool.entity
  global-config:
    banner: false
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
#分页pageHelper
pagehelper:
  helperDialect: mysql
  reasonable: false
  support-methods-arguments: false
  page-size-zero: false