## MainTests

### 测试接口
POST http://localhost:8056/student/pageSo
Content-Type: application/json

{
  "name": "张飞",
  "age": 0,
  "pageNum": 1,
  "pageSize": 10
}
### 测试接口
GET http://localhost:8056/product/page?pageNum=1&pageSize=10
Content-Type: application/json

### 测试网关
GET http://localhost:12000/product/product/page?pageNum=1&pageSize=10
Content-Type: application/json

### 测试接口
GET http://localhost:8055/order/page?pageNum=1&pageSize=10
Content-Type: application/json

### 测试网关
GET http://localhost:12000/order/order/page?pageNum=1&pageSize=10
Content-Type: application/json

### 测试网关
POST http://localhost:12000/order/order/insert?productId=2
Content-Type: application/json

###
