## 产品测试

### 测试接口
GET http://localhost:8055/order/page?pageNum=1&pageSize=10
Content-Type: application/json

### 测试接口
GET http://localhost:12000/order/order/page?pageNum=1&pageSize=10
Content-Type: application/json


### 插入订单
POST http://localhost:8055/order/insert?productId=2
Content-Type: application/x-www-form-urlencoded


